#!/bin/sh
# Universal launcher script for Linux

cd "$(dirname $0)"

LOVE="bin/love-{LOVEVERSION}-$(uname -m).AppImage"
if [ ! -f "$LOVE" ] ; then
    LOVE="bin/love-{LOVEVERSION}-i686.AppImage"
fi

$LOVE "$(pwd)/lib/{BUNDLENAME}"
